name: Spring App CI/CD Pipeline

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Create application.properties
      run: |
        echo "${{ secrets.APP_PROPERTIES }}" > src/main/resources/application.properties
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/pol-back:latest
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/pol-back:cache
        cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/pol-back:cache,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/pol-back:latest
          docker stop pol-back || true
          docker rm pol-back || true
          docker run -d --name pol-back -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/pol-back:latest
